theme: jekyll-theme-slate
<title>
   {%if page.title %}
       {{ page.title }}
   {% else %}
       {{ site.title }}
   {% endif %}
</title>
title: myCustomTitle
description: myCustomAndDetailedDescription
title: Push to Data
